# C 端用户前端
server {
  listen 80;
  server_name app.example.com;
  client_max_body_size 5m; # 文件走 MinIO 直传，这里仅 API/SSR
  location / {
    proxy_pass http://web:3000;
    include /etc/nginx/conf.d/_proxy.inc;
  }
}

# 运营管理后台（后续加 IP 白名单 allow/deny）
server {
  listen 80;
  server_name admin.example.com;
  location / {
    proxy_pass http://admin:3001;
    include /etc/nginx/conf.d/_proxy.inc;
  }
}

# App API
server {
  listen 80;
  server_name api.example.com;
  location / {
    proxy_pass http://api:8080;
    include /etc/nginx/conf.d/_proxy.inc;
  }
}
